### ISSUE TITLE
Is there any issue with releasing in Google PlayStore?

### ISSUE THREAD

**Issue by writingdeveloper** [shaqian/flutter_ssh#65]
I have an issue that when I build release mode to create app bundle. It works.

And I upload the APK file to directly my phone and install it and it works.

And also When I upload APK file to 3rd party App store Galaxy Store or Onestore it also works fine.

But When I upload to Google Play store, it uploads well but When I download app from Google playstore it only shows start screen and it closed without any error message.

Is there any problem with Google play store with flutter_ssh package?

**Comment by ahoelzemann** [comment]
@writingdeveloper I'm using flutter_ssh in my app without problems regarding the play store. I think that this bug is coming from somewhere else. Try to implement an error log, that writes the exceptions in an logfile. You can do that for example with https://pub.dev/packages/fimber_io and https://pub.dev/packages/flutter_fimber_filelogger

**Comment by writingdeveloper** [comment]
@ahoelzemann Thanks! I'll check it out.
